### ISSUE TITLE
Unable to save and load models

### ISSUE THREAD

**Issue by canbooo** [TyXe-BDL/TyXe#14]
Is there a way to save and load models, especially the ones using MCMC? I was hoping to use something along the lines of `pyro.get_param_store` but [it does not work with MCMC apparently](https://forum.pyro.ai/t/save-mcmc-results/428).

**Comment by ucl-jhr** [comment]
We don't implement any saving/loading functionality beyond what Pytorch and Pyro provide unfortunately.

I won't have time to experiment with this myself in the near future, but if you're happy to modify your TyXe version locally, you could try, instead of storing the MCMC object as an attribute on the `MCMC_BNN` instance [as we currently do](https://github.com/TyXe-BDL/TyXe/blob/9b0a0aebb84ddd7eed2f26da967e61ad0cb79039/tyxe/bnn.py#L272), to just keep the samples dictionary from the MCMC run and save/load that attribute. That would require slightly modifying the `predict` function accordingly.

**Comment by canbooo** [comment]
Worked as intended. Thank you very much! Hit me up, if you decide to offer saving/loading functionality and require a PR.
